# =========================================================
# MODEL
# =========================================================

vocab_size: 16000

block_size: 256

n_layer: 12
n_head: 12
d_model: 768

dropout: 0.1

# =========================================================
# TRAINING
# =========================================================

batch_size: 4
accumulation_steps: 16

learning_rate: 0.0002
min_lr: 0.00002

max_iters: 12000

eval_interval: 100
eval_iters: 20

# =========================================================
# OPTIMIZER
# =========================================================

weight_decay: 0.1

beta1: 0.9
beta2: 0.95

grad_clip: 1.0

# =========================================================
# SCHEDULER
# =========================================================

warmup_steps: 500

# =========================================================
# SYSTEM
# =========================================================

device: "cuda"

dtype: "float16"